# Paths to be ignored by addlicense
ignorePaths: ["test/**"]

# File extension commenting format configuration
fileExtensions:
  - extensions: [".c", ".h"]
    top: "/*"
    mid: " * "
    bot: "*/"
  - extensions: [".js", ".mjs", ".cjs", ".jsx", ".tsx", ".css", ".tf", ".ts"]
    top: "/**"
    mid: " * "
    bot: "*/"
  - extensions:
      [
        ".cc",
        ".cpp",
        ".cs",
        ".go",
        ".hh",
        ".hpp",
        ".java",
        ".m",
        ".mm",
        ".proto",
        ".rs",
        ".scala",
        ".swift",
        ".dart",
        ".groovy",
        ".kt",
        ".kts",
        ".php",
      ]
    top: ""
    mid: "// "
    bot: ""
  - extensions:
      [
        ".py",
        ".sh",
        ".yaml",
        ".yml",
        ".dockerfile",
        "dockerfile",
        ".rb",
        "gemfile",
      ]
    top: ""
    mid: "# "
    bot: ""
  - extensions: [".el", ".lisp"]
    top: ""
    mid: ";; "
    bot: ""
  - extensions: [".erl"]
    top: ""
    mid: "% "
    bot: ""
  - extensions: [".hs", ".sql"]
    top: ""
    mid: "-- "
    bot: ""
  - extensions: [".html", ".xml", ".vue"]
    top: "<!--"
    mid: " "
    bot: "-->"
  - extensions: [".ml", ".mli", ".mll", ".mly"]
    top: "(**"
    mid: "   "
    bot: "*)"
